export const SET_APUNTADOR = 'SET_APUNTADOR_TRANSACTION';
export const SET_RULE = 'SET_RULE_TRANSACTION';
export const SET_GOOUT = 'SET_GOOUT_TRANSACTION';
export const SET_RULES = 'SET_RULES_TRANSACTION';
export const SET_SALDO = 'SET_SALDO_TRANSACTION';
